# Generated by Django 2.1.13 on 2019-10-20 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='Billview',
            fields=[
                ('billno', models.IntegerField(primary_key=True, serialize=False)),
                ('billname', models.CharField(blank=True, max_length=80, null=True)),
                ('billlink', models.CharField(blank=True, max_length=34, null=True)),
                ('proposerkind', models.CharField(blank=True, max_length=10, null=True)),
                ('proposerdt', models.CharField(blank=True, max_length=10, null=True)),
                ('submitdt', models.CharField(blank=True, max_length=10, null=True)),
                ('committeename', models.CharField(blank=True, max_length=20, null=True)),
                ('procdt', models.CharField(blank=True, max_length=10, null=True)),
                ('generalresult', models.CharField(blank=True, max_length=10, null=True)),
                ('summarycontent', models.TextField(blank=True, null=True)),
                ('billstep', models.CharField(blank=True, max_length=10, null=True)),
                ('finished', models.BooleanField(blank=True, null=True)),
                ('done', models.BooleanField(blank=True, null=True)),
                ('coactors', models.TextField(blank=True, null=True)),
                ('billid', models.ForeignKey(blank=True, db_column='billid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Bill')),
            ],
            options={
                'db_table': 'billview',
            },
        ),
        migrations.CreateModel(
            name='BillviewBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Bill')),
                ('billno', models.ForeignKey(blank=True, db_column='billno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Billview')),
            ],
            options={
                'db_table': 'billview_bill',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
