# Generated by Django 2.1.13 on 2019-10-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bill_billview_billviewbill_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billviewbill',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billviewbill',
            name='billno',
        ),
        migrations.DeleteModel(
            name='BillviewBill',
        ),
    ]
