# Generated by Django 2.1.13 on 2019-11-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191020_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='billview',
            name='committeename',
        ),
        migrations.AlterField(
            model_name='billview',
            name='billid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Bill'),
        ),
    ]
