# Generated by Django 2.1.13 on 2019-11-19 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191118_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='committee',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Committee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billview',
            name='committee',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Committee'),
            preserve_default=False,
        ),
    ]
