# Generated by Django 2.1.13 on 2019-11-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191119_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
