# Generated by Django 2.1.13 on 2019-11-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191119_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billview',
            old_name='billid',
            new_name='bill',
        ),
    ]
