# Generated by Django 2.1.13 on 2019-11-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191119_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='billview',
            name='alternative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billviews', to='core.Billview'),
        ),
        migrations.AddField(
            model_name='billview',
            name='status',
            field=models.CharField(choices=[('NORM', '의안'), ('ALT', '대안'), ('DISC', '대안반영폐기')], default='NORM', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='committee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.Committee'),
        ),
        migrations.AlterField(
            model_name='billview',
            name='bill',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='billviews', to='core.Bill'),
        ),
        migrations.AlterField(
            model_name='billview',
            name='committee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='billviews', to='core.Committee'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscribe_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to='core.Bill'),
        ),
    ]
