# Generated by Django 2.1.13 on 2019-12-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191126_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='lastUpdated',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
