# Generated by Django 2.1.13 on 2019-12-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191211_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='lastUpdated',
            new_name='lastupdated',
        ),
    ]
